#!/bin/bash
# asoundrc v0.1.0 20090101 markc@renta.net GPLv3
# asoundrc v0.2.0 20090320 quatro_por_quatro@yahoo.es GPLv3
# asoundrc v0.3.0 20210414 waytoarcher@gmail.com GPLv3
#
# A simple script to create a particular default audio device regardless
# of what cards are loaded or in what order. It could be used anytime or
# placed in a ~/.bashrc script for a persistent setup every login.
#
# Usage: asoundrc [DEFAULT_CARD] ，will save to ~/.asoundrc

# use the first parameter as the card name, or else
# look for the sound card, discarding those that are only microphones
# when there are multiple cards, use the first one

function check_word_in_array() {
    word=$1
    array=$2
    for s in ${array[*]}; do
        if [ "${word}" == "${s}" ]; then
            result=$word
            echo "${result}"
        fi
    done
}
function help() {
    echo "A simple script to create a particular default audio device regardless
of what cards are loaded or in what order.
Usage: asoundrc [DEFAULT_CARD] ，the conf will save to ~/.asoundrc
	"
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ]; then
    help
    exit 0
fi

if default_card="${1:-$(cat "$(for f in $(ls -1 /proc/asound/card[0-9]*/{midi,codec}* 2> /dev/null); do echo "${f%/*}"; done \
    | sed -e '\|^[\[:blank:]\]$|d' -e 'q')/id" 2> /dev/null)}"; then
    read -ra soundcards <<< "$(cat /proc/asound/card[0-9]*/id 2> /dev/null | tr "\n" " ")"
    soundcardsum=${#soundcards[*]}
    cardname=$(check_word_in_array "$1" "${soundcards[*]}")
    echo $cardname
    if [ -z "$cardname" ]; then
        cat -n /proc/asound/card[0-9]*/id 2> /dev/null
        read -rp "Please input default output sound card num: " cardnu
        if [[ "${cardnu}" -gt "${soundcardsum}" ]]; then
            echo "Please check the sound card num."
            exit 1
        fi
        default_card="${soundcards[$cardnu - 1]}"
    fi

    echo "Using sound card: ${default_card}" >&2
      cat /proc/asound/card[0-9]*/id \
        | gawk --assign default_card="${default_card}" \
            '{print "pcm."$1" { type hw; card "$1"; }\nctl."$1" { type hw; card "$1"; }" }
      END {print "pcm.!default pcm."default_card"\nctl.!default ctl."default_card}' | tee "$HOME"/.asoundrc
else
    echo "Warning: No sound cards found." >&2
fi
