#!/bin/bash
#by sandylaw <waytoarcher@gmail.com> 2021-05-18
if ! [ "$(id -u)" -eq 0 ]; then
    echo "Please run $0 with root."
    exit 0
fi
out() { printf "%s %s\n%s\n" "$1" "$2" "${@:3}"; }
msg() { out "==>" "$@"; }
function help() {
    msg "bash $0 on/off"
    exit 0
}
case $1 in
    -h | --help | -H | --HELP | help | h | H | HELP)
        help
        ;;
    *) ;;
esac

notify_switch=${1:-on}

session_conf=/etc/dbus-1/session.d/session-local.conf
function reload_dbus() {
    dbus-launch --auto-syntax
}
function disable_notify() {
    true > ${session_conf}
    cat >> ${session_conf} << EOF
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
   "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
  <busconfig>
    <!-- Our well-known bus type, don't change this -->
    <type>session</type>
  
    <!-- If we fork, keep the user's original umask to avoid affecting
         the behavior of child processes. -->
    <keep_umask/>
  
    <listen>unix:tmpdir=/tmp</listen>
  
    <auth>EXTERNAL</auth>
  
    <standard_session_servicedirs />
  
    <policy context="default">
      <!-- Allow everything to be sent -->
      <allow send_destination="*" eavesdrop="true"/>
      <!-- Allow everything to be received -->
      <allow eavesdrop="true"/>
      <!-- Allow anyone to own anything -->
      <allow own="*"/>
      <deny send_destination="com.deepin.dde.Notification"/>
      <deny send_destination="com.deepin.dde.osd"/>
      <deny send_destination="com.deepin.welcome.osd"/>
      <deny send_destination="com.deepin.dde.WarningDialog"/>
    </policy>
  
  </busconfig>
EOF
}
function enable_notify() {
    rm -rf ${session_conf} || true
}

if [ on == "$notify_switch" ]; then
    enable_notify
    reload_dbus
elif [ off == "$notify_switch" ]; then
    disable_notify
    reload_dbus
else
    help
    exit 1
fi
