#!/bin/bash
PROXY_STRIN=""
export http_proxy=$PROXY_STRIN
export HTTP_PROXY=$PROXY_STRIN
export HTTPS_PROXY=$PROXY_STRIN
export https_proxy=$PROXY_STRIN
export socks_proxy=$PROXY_STRIN
export all_proxy=$PROXY_STRIN
export SOCKS_PROXY=$PROXY_STRIN
export ALL_PROXY=$PROXY_STRIN
